### PR TITLE
Index support (WIP)

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I'm currently implementing basic support for indices (simple and unique). My branch already creates simple and unique indices, but it's all still very rough :)

Next steps will be:
- Support for Compound Keys
- Figuring out a nice way to pass index options
- Some sugar: MyModel.index(:property) and .unique(:property)
- Delve into EmbeddedValue work in dm-core
- And, of course, some specs

I'll update the Pull Requests with more commits.

Best regards,
Lars

### CODE REVIEW

**Comment by ghost** [comment]
Ah, forgot an example:

``` ruby
class MyModel
  include DataMapper::Mongo::Resource

  property :id, ObjectId
  property :name, :index => true
  property :uuid, :unique => true
end
```

Indices will be created when auto_migrating.

**Comment by solnic** [comment]
Thanks man! I prefer to have a single commit per feature along with proper spec coverage of course. Currently spec suite is a bit of a mess, but the approach we're taking is similar to how spec suite is organized in Veritas project (see https://github.com/dkubb/veritas for a reference) and from now on every spec should be written like that. I'll be porting/rewriting existing specs to match the new approach.

Feel free to ping me if you have any questions, either here or on #datamapper irc channel or via gtalk.

**Comment by ghost** [comment]
Yeah, I thought so, just opened the Pull Request to let everyone know that someone is working on index support and to get a bit of feedback. In the end I'll prepare a big merge commit with specs.

What do you think about the approach via auto_migrate? It seemed reasonable to not do implicit model changes in order to be consistent with other DM adapters.

**Comment by solnic** [comment]
Yeah it is inline with other adapters which is definitely what we want.

**Comment by mbj** [comment]
What is the state of this @lgierth do you plan to finish?

**Comment by ghost** [comment]
I'm not using MongoDB anymore so I'd be happy to see someone else pick up.

**Pull request closed without merging**
