### PR TITLE
Fixed DBRefs

### PR DESCRIPTION
**Pull request by mbj**
- field names now default on property name
- dbrefs are no longer a key by default

The default field name "_id" collides with ObjectID. The use of a DBRef in a model creates an (most times unwanted) implict CPK.

I just duplicated the implementation of ObjectID outmitting the wrong defaults.

### CODE REVIEW

**Comment by solnic** [comment]
Would it work if you just set field to nil and key to false and still have it inherit from ObjectId?

**Comment by mbj** [comment]
I do not know the property API in deep, so I duplicated the code. I thought setting field to nil would not trigger the code to use property.name as field.

But why not do it the other way round.

ObjectID could inherit from DBRef, so ObjectID ist _just_ a DBRef with defaults for key => true and field => "_id" ?

**Comment by mbj** [comment]
Just changed the code just like mentioned above. Now it does the job more cleanly.

**Comment by solnic** [comment]
I think this should work:

``` ruby
class DBRef < ObjectId
  key false
  field nil
end
```

**Comment by mbj** [comment]
I added a commit to this pull request which does it the other way round. (The duplication is gone)

ObjectID inherits from DBRef and sets the key to true and field to "_id". This maps cleanly to the required behavior. DBRef is "just" a reference to some Object, and ObjectID is a "specialized" DBRef with some defaults.

In your suggested solution key would be set to true in ObjectID and would be overridden by DBRef with false, I dislike to set something and to override it again when this is avoidable.

**Comment by mbj** [comment]
@solnic, is there anything left until you can merge this?

**Comment by solnic** [comment]
@mbj I need some time to review all of this. Do these changes require dm-core's updated adapter shared specs too?

**Comment by mbj** [comment]
No they do not.

There is a separate pull request on the spec-improvement branch.

**Comment by mbj** [comment]
@solnic, Identified a potentional problem with my remove of cleanup_model usage in ac4de64, the before :all block in spec_helper only fires once? Maybe you should skip this commit. All specs still pass, anyway.
If this ugly chain of commits makes it "to hard" for a clean merge, I can "polish" it based on your suggestions.

**Comment by solnic** [comment]
@mbj I finally merged it in. Seems like we have some failures: http://ci.datamapper.org/view/dm%20adapters/job/dm-mongo-adapter/60/rubyvm=1.8.7/console

**Comment by mbj** [comment]
@solnic Never saw these failures in my local spec runs. I'll try to reproduce and fix. Thx for merging.

**Comment by solnic** [comment]
@mbj I also noticed that aggregates spec completely hangs my mongodb 
instance...and I can reproduce the freaking authorization failure 
locally...damn, we gotta clean up those things :)

**Comment by mbj** [comment]
@solnic Sitemark: Is a dm spec responsible for setting up a connection when needed? Or should an active connection be expected? Is there something like DataMapper.unsetup to explicitly terminate a connection?

**Comment by solnic** [comment]
@mbj There used to be a line in adapter.rb which explicitly closes the connection, now I don't see it :/

**Comment by mbj** [comment]
@solnic: What happens when I do DataMapper.setup(:default,connection_string_a) and afterwards DataMapper.setup(:default,connection_string_b), is there anything evil expected? (Im assuming there are no living records).

**Comment by mbj** [comment]
s/living records/record instances in the current ruby process/

**Pull request merged**
