### PR TITLE
Fixed authentication issue?

### PR DESCRIPTION
**Pull request by mbj**
Hi solnic,

I just played around with your dm-mongo-adapter. Tried to ran the specs, but always got authentication problems.

The connection options where providing only @options[:user], the code used @options[:username], so all the time nil was passed to mongo authentication.

Feel free to pull or comment my submission!

Regards,

Markus

### CODE REVIEW

**Comment by solnic** [comment]
Thanks, unfortunately it didn't fix the failures: http://ci.datamapper.org/view/All/job/dm-mongo-adapter/rubyvm=1.8.7/54/console :/ I'm gonna look into it later

**Comment by mbj** [comment]
I forgot to mention I'm on ruby-1.9.2-p180. When todays work is done I'll try to check for ruby-1.8.7.

**Comment by solnic** [comment]
On 1.9.2. it fails too http://ci.datamapper.org/view/All/job/dm-mongo-adapter/54/rubyvm=1.9.2/console This is a tricky issue since we've been seeing these failures for a long time but sometimes the build was green. I also couldn't reproduce it locally so something is definitely wrong :)

**Comment by mbj** [comment]
Maybe you should add some ugly debug prints to see where the difference in ci environment comes from?
I'll try to push the dm-mongo-adapter to our own ci later. 4 eyes are better than two ;)

**Comment by mbj** [comment]
This is so crazy sometimes :user is the key, and other times :username is the key... It seems to be depended on the active gems.

**Pull request merged**
