### PR TITLE
Preserve microseconds in DateTime

### PR DESCRIPTION
**Pull request by dkubb**
This patch makes sure the `Time` object passed to MongoDB has the microseconds from `DateTime`. This code has been tested on 1.8 and 1.9 where `DateTime#sec_fraction` has different behavior.

Without this patch, microseconds will be truncated to 0 when persisted, and when the value is fetched back from MongoDB it will not match the original. This can sometimes cause problems in specs that test objects have round tripped properly, and can be quite confusing to debug since the `#inspect` and `#to_s` outputs do not display any differences.

### CODE REVIEW

**Comment by dkubb** [comment]
Also, I can include specs but I didn't see any for the original DateTime.to_mongo method. Let me know the path where you'd like the specs to go and I can include some.

**Comment by solnic** [comment]
Thanks Dan. Cleaning up specs and adding missing ones is on my todo list. I want to use a similar approach to specs as you did with veritas. Anthony (antw) started rewriting specs a year ago but has never managed to finish hence the "legacy" directory is still there. I also want to look into our shared adapter specs and see if they can be refactored and maybe even extended with new examples. General code clean-up is also required (as you probably noticed :)). I just added you as a collaborator to the project, just so you know :)

**Comment by dkubb** [comment]
@solnic: Ok, so I'll add a spec where I would've added it according to the conventions I used in veritas. If you don't like it then you can move it wherever you wish ;)

**Comment by solnic** [comment]
awesome!

**Pull request closed without merging**
